pool:
  name: Azure Pipelines
variables:
  imagename: 'medhaimageyaml'

steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'sriharsha devops-terraform-on-azure-with-azure-devops'
    azureContainerRegistry: '{"loginServer":"acrmedha2303.azurecr.io", "id" : "/subscriptions/f456dd18-85da-45af-a9f6-372811f73b09/resourceGroups/docker-group/providers/Microsoft.ContainerRegistry/registries/acrmedha2303"}'
    dockerFile: WebAppgit1/Dockerfile
    imageName: '$(imagename)'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'sriharsha devops-terraform-on-azure-with-azure-devops'
    azureContainerRegistry: '{"loginServer":"acrmedha2303.azurecr.io", "id" : "/subscriptions/f456dd18-85da-45af-a9f6-372811f73b09/resourceGroups/docker-group/providers/Microsoft.ContainerRegistry/registries/acrmedha2303"}'
    action: 'Push an image'
    imageName: '$(imagename)'
    includeLatestTag: true
